language: rust

cache: cargo

rust:
  - stable
  - nightly

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

git:
  depth: 10

before_script:
  - if [ "$TRAVIS_RUST_VERSION" == "nightly" ]; then chmod +x benches-compare.sh; fi

script:
  - cargo build --verbose --all
  - cargo build --verbose --all --features "dot"
  - if [ "$TRAVIS_RUST_VERSION" == "nightly" ]; then
    cargo +nightly build --features "no_std dot" --verbose --all;
    fi
  - cargo test --verbose --all
  - cargo test --verbose --all --features "dot"
  - if [ "$TRAVIS_RUST_VERSION" == "nightly" ]; then
      cargo +nightly test --features "no_std dot" --verbose --all;
    fi

after_script:
  - if [ "$TRAVIS_RUST_VERSION" == "nightly" ]; then chmod +x benches-compare.sh; fi
