language: rust

cache: cargo

rust:
  - stable
  - nightly

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

git:
  depth: 10

before_script:
  - chmod +x benches-compare.sh

script:
  - cargo build --verbose --all
  - if [ "$TRAVIS_RUST_VERSION" == "nightly" ]; then
    cargo build --featues no_std --verbose --all;
    fi
  - cargo test --verbose --all
  - if [ "$TRAVIS_RUST_VERSION" == "nightly" ]; then
      cargo test --featues no_std --verbose --all;
      fi


after_script:
  - ./benches-compare.sh
  -