[package]
name = "graphlib"
version = "0.2.1"
authors = ["Octavian Oncescu <octavonce@gmail.com>"]
edition = "2018"
repository = "https://github.com/purpleprotocol/graphlib"
keywords = ["graph", "data-structure", "mutable", "graph-algorithm"]
categories = ["data-structure"]
description = "Graphlib is a simple and powerful rust library for the graph data-structure."
license = "MIT"
readme = "README.md"

[badges]
travis-ci = { repository = "purpleprotocol/graphlib", branch = "master" }

[dependencies]
rand = "0.6.0"
hashbrown = { version = "0.1", features = ["rayon"] }

[dev-dependencies]
criterion = "0.2.10"

[[bench]]
name = "benchmark"
harness = false