[package]
name = "graphlib"
version = "0.1.0"
authors = ["Octavian Oncescu <octavonce@gmail.com>"]
edition = "2018"

[dependencies]
rand = "0.6.0"
hashbrown = { version = "0.1", features = ["rayon"] }
