[package]
name = "graphlib"
version = "0.1.0"
authors = ["Octavian Oncescu <octavonce@gmail.com>"]
edition = "2018"
repository = "https://github.com/purpleprotocol/graphlib"
keywords = ["graph", "data-structure", "mutable", "graph-algorithm"]

[badges]
travis-ci = { repository = "purpleprotocol/graphlib", branch = "master" }

[dependencies]
rand = "0.6.0"
hashbrown = { version = "0.1", features = ["rayon"] }
